### ISSUE TITLE
Possible corner cases in ESJwsTool 

### ISSUE THREAD

**Issue by WouterTinus** [PKISharp/ACMESharpCore#17]
We had one user that seemed to get the wrong tokens whatever they tried to validate. @webprofusion-chrisc pointed out that there may be very sneaky bugs regarding the serialization of *some* EC keys: https://github.com/PKISharp/win-acme/issues/1001#issuecomment-457800713.

Then I looked into the ACMESharpCore code and found this comment in ESJswTool.cs, line 83

`// TODO: this is inefficient and corner cases exist that will break this -- FIX THIS!!!`

Somehow this users problem disappeared after he installed ASP.NET on the machine, but I'm worried it might come back and bite us in the face.

**Comment by WouterTinus** [comment]
I added a PR #18 to lock down the field ordering as a precaution. I also added a test case that stresses the serialization/deserialization mechanism by a generating a thousand new instances, signing ~8KB of random data with each of them, serializing the key information, importing the key into an another instance and checking the signature. Locally I probably ran that 50.000 times without problems. So the corner cases, if there, must be rare.

**Comment by webprofusion-chrisc** [comment]
Hi, I confused the issue by mentioning two account key bugs in one comment - the serialization order issue affects users in some locales - the default sorting of serialized properties in .net varies especially for some users (in latvian etc).

Regarding the account keys occasionally hashing wrong, that was byte padding of the EC curve x/y where the encoded result should be a certain number of bytes long but was one short in some cases (using a particular bouncy castle method), this was OK for general signing use because the X/Y still falls on the correct part of the EC curve but manifested as a challenge failure for DNS because the result is used as a hash.

**Comment by WouterTinus** [comment]
I'm guilty of the same. The PR addresses the serialization order issue, the new unit test is an attempt to trigger the second one.

AcmeSharpCore doesn't use BouncyCastle but the comment is worrying and the user issue was extremely weird, so I went hunting for a similar class of bug. Perhaps I should look into a way to involve the  ChallengeDecoder into the stress test.

**Comment by ebekker** [comment]
I'm closing this out since the associated PR has already been merged and it's been a while.  If there's still an issue, please reopen and we can dive in.
