### ISSUE TITLE
Pre-Authorization support

### ISSUE THREAD

**Issue by lol768** [PKISharp/ACMESharpCore#20]
Does this client support Pre-Authorization as described in https://tools.ietf.org/html/draft-ietf-acme-acme-12#section-7.4.1?

**Comment by lol768** [comment]
![](https://lol768.com/i/NiggazAutomatesGendarmeTrumping)

Well, great. Guess there's not much point implementing this.

**Comment by ebekker** [comment]
There are 3 main features of the current spec that are not implemented as listed [here](https://github.com/PKISharp/ACMESharpCore/tree/master/src/ACMESharp#whats-not-implementednot-working).

LE's Boulder doesn't implement pre-authz because it doesn't really apply for their situation, since they are heavily dependent on automation for authorizations.  It would make more sense for a commercial CA that offers alternative/out-of-band methods.
