### ISSUE TITLE
What happened to the Vault?

### ISSUE THREAD

**Issue by joshuapetryk** [PKISharp/ACMESharpCore#23]
Hey, I am very interested in utilizing and potentially contributing to ACMESharp and ACMESharpCore. I noticed that there doesn't seem to be a notion of the Vault in Core. Was this interface removed? If so - are there any plans to port the Vault over? How should we be handling state now?

**Comment by ebekker** [comment]
The Vault was a secondary artifact in the original ACMESharp project.  One of the reasons I created it was because I layered the PowerShell module atop the .NET client library and I needed a good way to store state and sensitive artifacts.

In the new Core version, I haven't ported or implemented the PWSH layer, and while the Vault piece can be ported over as a storage mechanism, there wouldn't really be anything that uses it yet.  Do you have a scenario where you're using the ACME client library and the Vault library outside of PWSH?

In general I leave it up to each user and their own use case to come up with their own mechanism for storing the state.  In my unit and integration tests, I just simply serialize the artifacts as JSON files between test stages.

In the various [examples](https://github.com/PKISharp/ACMESharpCore/tree/master/src/examples), I use slightly different implementations, but they all basically revolve around serializing the artifacts as a JSON file or files to a directory.

For example, the [CLI](https://github.com/PKISharp/ACMESharpCore/tree/master/src/examples/ACMECLI) just uses a directory (defaults to current) to store individual state files.  The [ASP.NET Core](https://github.com/PKISharp/ACMESharpCore/tree/master/src/examples/ACMEKestrel) example essentially does the same thing, but has single consolidated state object and thus a single file for its own state data implementation, since it's focused more narrowly on its use case.

**Comment by cbre-jpetryk** [comment]
hey sorry for the delay in getting back. my use case would using a cloud provider vault, such as Azure Storage, Azure Key Vault, Amazon S3 or Amazon KMS.

I have been working on a solution to automatically keep our certificates up to date, but we're trying to move towards more cloud native solutions instead of local file system. I would love to have the vault interface to write some concrete implementations for the above mentioned services.

Thanks for sharing some context! If I get some time I'll look at making a PR.

**Comment by joshuapetryk** [comment]
hey sorry for the delay in getting back. my use case would using a cloud provider vault, such as Azure Storage, Azure Key Vault, Amazon S3 or Amazon KMS.

I have been working on a solution to automatically keep our certificates up to date, but we're trying to move towards more cloud native solutions instead of local file system. I would love to have the vault interface to write some concrete implementations for the above mentioned services.

Thanks for sharing some context! If I get some time I'll look at making a PR.

**Comment by ebekker** [comment]
I'll close this ticket out for now, if you get around to that PR, we can resurrect it.
