### ISSUE TITLE
OWIN Integration

### ISSUE THREAD

**Issue by kieronlanning** [PKISharp/ACMESharpCore#24]
I know it's old now, but we're stilling maintaining an old Azure Cloud Services project that we're converting over to use Windows Containers (can't move to .NET Core for this project), and a working example of integrating this with OWIN would be ace! ...anyone tried?

**Comment by ebekker** [comment]
Because the core libraries are .NET Standard-based, it may work, but I haven't tried.  What version of the Framework are you targeting?  You may be able to adapt the example [ASP.NET Core example](https://github.com/PKISharp/ACMESharpCore/tree/master/src/examples/ACMEKestrel) to your scenario, although, I'm not sure what the equivalent of an `[IHostedService](https://github.com/PKISharp/ACMESharpCore/blob/master/src/examples/ACMEKestrel/AcmeExtensions.cs#L36) would be in your environment.

But I only use that in the example to implement a background-running task, you can substitute something like Hangfire or whatever makes sense to implement that.

**Comment by kieronlanning** [comment]
Thanks @ebekker I'll take a look. We're using .NET 4.8 and we can craft an equivalent of an `IHostedService` without issue.
