### ISSUE TITLE
ACMECLI example code does not export private key with PKCS12

### ISSUE THREAD

**Issue by cdoc83** [PKISharp/ACMESharpCore#25]
If the option --export-pfx [filename] is ran as shown [in these instructions](https://github.com/PKISharp/ACMESharpCore/tree/master/src/examples/ACMECLI) with the following command example, the private key is not added to the export:

acmecli --dns myapp.example.com --dns myapp-0.example.com --dns myapp-1.example.com --export-pfx mycertificate.pfx

This can be verified by running the example code in debug mode, and investigating the cert object currently being created on [line 539](https://github.com/PKISharp/ACMESharpCore/blob/627219b9feff9a9b880cb98cc02cf7b357a0e317/src/examples/ACMECLI/Program.cs#L539).  The property HasPrivateKey will be false.  This can also be verified by checking the certificate after export.  It does not contain the private key.  This is the code block referenced around line 539, with an additional comment:

```
if (ExportPfx != null)
{
    Console.WriteLine("Exporting Certificate as PKCS12...");
    using (var cert = new X509Certificate2(LoadRaw<byte[]>(true, Constants.AcmeOrderCertFmt, orderId)))
    {
        // cert.HasPrivateKey is false!
        await File.WriteAllBytesAsync(ExportPfx, cert.Export(X509ContentType.Pkcs12));
    }
}

```

**Comment by ebekker** [comment]
You are correct, the exported PFX does not contain the private key because the raw certificate object that's being loaded in from disk at this point is only the public certificate file pulled in from the ACME CA, it does not include the private key component.

I'll have to look into this a little bit to see how to combine the two together, at first glance it doesn't look like `X509Certificate2` has a way to associate these two separately.

**Comment by ebekker** [comment]
Thanks to @olibos for contributing the initial support for exporting the private key!  As he pointed out in his comments, that initial support only allowed importing of RSA keys, due to limitations in the BCL classes in .NET Core for exporting/importing ECDSA private keys.

In order to better support both RSA and EC keys, I've rewrote the CLI example to make use of the [PKISharp.SimplePKI](https://github.com/PKISharp/ACMESharpCore/tree/master/src/PKISharp.SimplePKI) library -- after all, this is exactly one of the limitations that library was written for.

So I just committed the updated sample CLI code.  It actually slightly reverts the behavior that was there before, in that the `--export-pfx` switch now _only_ exports the certificate chain.  You have to add the `--export-pfx-password` switch in order to include the private key as well (both RSA and ECDSA supported).  And you can force an empty (no) password by using a single-space character password, that will be interpreted as a signal for exporting the private key but no password.
